### ISSUE TITLE
Show color palette of listed themes

### ISSUE THREAD

**Issue by orhanbalci** [shuhei/colortty#11]
When choosing a theme seeing color palette is important if theme is not a well known one.  Add an option to show color palette on terminal.  [Pastel](https://github.com/sharkdp/pastel) project would be helpful in implementing this.

**Comment by shuhei** [comment]
This will be a really nice feature. We'll need cache the github repo contents instead fetching on demand because colortty needs to get individual files to know the colors in them.

**Comment by shuhei** [comment]
Released as `0.2.0`
