### ISSUE TITLE
Add Gogh color scheme support

### ISSUE THREAD

**Issue by orhanbalci** [shuhei/colortty#5]
Hi there. First of all thanks for this helpful utility tool. I don't know if you are willing to push forward and add some more functionality. 

Add support for themes in [Gogh](https://github.com/Mayccoll/Gogh)

**Comment by shuhei** [comment]
Thanks for your suggestions! I implemented Gogh color support, and will release the change soon.

**Comment by orhanbalci** [comment]
Awesome! Thanks for the effort.
